name: Build 14
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=7168
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install Packages
        run: yarn install

      - name: Build
        run: yarn build
